"""Add cascade delete to HabitLog

Revision ID: 27cdcc3e56e0
Revises: 676d1f6bb044
Create Date: 2026-03-05 10:27:35.245764

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "27cdcc3e56e0"
down_revision: str | Sequence[str] | None = "676d1f6bb044"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("habitlog_habit_id_fkey"), "habitlog", type_="foreignkey")
    op.create_foreign_key(
        None, "habitlog", "habit", ["habit_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "habitlog", type_="foreignkey")
    op.create_foreign_key(
        op.f("habitlog_habit_id_fkey"), "habitlog", "habit", ["habit_id"], ["id"]
    )
    # ### end Alembic commands ###
