"""init

Revision ID: 4279a8e05696
Revises:
Create Date: 2025-12-19 14:40:00.743914

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "4279a8e05696"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
